main: com.github.dawsonvilamaa.nationsandvillagesplugin.Main
name: NationsAndVillagesPlugin
version: 1.0
author: Dawson Vilamaa and Derek Brown
description: Allows players to create nations and villages to rule over and adds functionality to villages and villagers
commands:
  claim:
    description: claims a chunk for your nation
    usage: /claim
    permission: NationsAndVillages.claim
    permission-message: You don't have permission to use that command
  nation:
    aliases: nations
    description: creates a nation
    usage: /nation [create | info] [name]
    permission: NationsAndVillages.nation
    permission-message: You don't have permission to use that command
  unclaim:
    description: unclaims a chunk from your nation
    usage: /unclaim
    permission: NationsAndVillages.unclaim
    permission-message: You don't have permission to use that command