main: com.github.dawsonvilamaa.nationsandvillagesplugin.Main
name: NationsAndVillagesPlugin
version: 1.0
author: Dawson Vilamaa and Derek Brown
description: Allows players to create nations and villages to rule over and adds functionality to villages and villagers
commands:
  nation:
    description: creates a nation
    usage: /nation [create | info] [name]
    permission: TestPlugin.nation
    permission-message: You don't have permission to use that command